"""empty message

Revision ID: 02eec6dfd192
Revises: 25476460139b
Create Date: 2019-06-12 22:02:47.300430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eec6dfd192'
down_revision = '25476460139b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('riders_rider_id_fkey', 'riders', type_='foreignkey')
    op.create_foreign_key(None, 'riders', 'user', ['user_id'], ['id'])
    op.drop_column('riders', 'rider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'riders', type_='foreignkey')
    op.create_foreign_key('riders_rider_id_fkey', 'riders', 'rider', ['rider_id'], ['id'])
    op.drop_column('riders', 'user_id')
    # ### end Alembic commands ###
