"""empty message

Revision ID: 245e2642b8c0
Revises: e11e68d2a590
Create Date: 2019-08-07 03:14:32.669002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245e2642b8c0'
down_revision = 'e11e68d2a590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'driver', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.drop_column('driver', 'user_id')
    # ### end Alembic commands ###
