"""empty message

Revision ID: e11e68d2a590
Revises: 02eec6dfd192
Create Date: 2019-06-14 19:53:11.245049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e68d2a590'
down_revision = '02eec6dfd192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rider', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rider', 'user', ['user_id'], ['id'])
    op.add_column('riders', sa.Column('rider_id', sa.Integer(), nullable=False))
    op.drop_constraint('riders_user_id_fkey', 'riders', type_='foreignkey')
    op.create_foreign_key(None, 'riders', 'rider', ['rider_id'], ['id'])
    op.drop_column('riders', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'riders', type_='foreignkey')
    op.create_foreign_key('riders_user_id_fkey', 'riders', 'user', ['user_id'], ['id'])
    op.drop_column('riders', 'rider_id')
    op.drop_constraint(None, 'rider', type_='foreignkey')
    op.drop_column('rider', 'user_id')
    # ### end Alembic commands ###
